library MostModSINC version '0.0.003'

using QDM version '5.6'

codesystem "LOINC": 'urn:oid:2.16.840.1.113883.6.1'
valueset "Contraceptive Implant CPT Provision Procedures": 'urn:oid:2.16.840.1.113762.1.4.1166.180'
valueset "Contraceptive Implant Devices": 'urn:oid:2.16.840.1.113762.1.4.1166.201'
valueset "Contraceptive Implant HCPCS Devices": 'urn:oid:2.16.840.1.113762.1.4.1166.173'
valueset "Contraceptive Implant ICD10CM Provision Encounters": 'urn:oid:2.16.840.1.113762.1.4.1166.170'
valueset "Contraceptive Implant ICD10CM Surveillance": 'urn:oid:2.16.840.1.113762.1.4.1166.171'
valueset "Contraceptive Implant ICD10PCS Provision Procedures": 'urn:oid:2.16.840.1.113762.1.4.1166.162'
valueset "Contraceptive Implant LOINC": 'urn:oid:2.16.840.1.113762.1.4.1166.167'
valueset "Contraceptive Implant Provision Procedures": 'urn:oid:2.16.840.1.113762.1.4.1166.202'
valueset "Contraceptive Implant SNOMED Findings": 'urn:oid:2.16.840.1.113762.1.4.1166.164'
valueset "Contraceptive Implant SNOMED Provision Procedures": 'urn:oid:2.16.840.1.113762.1.4.1166.163'
valueset "Contraceptive Implant SNOMED Surveillance Procedures": 'urn:oid:2.16.840.1.113762.1.4.1166.192'
valueset "Contraceptive Implant Surveillance": 'urn:oid:2.16.840.1.113762.1.4.1166.203'
valueset "Contraceptive Implants RXNORM Medications": 'urn:oid:2.16.840.1.113762.1.4.1166.130'
valueset "Contraceptive Patch Devices": 'urn:oid:2.16.840.1.113762.1.4.1166.174'
valueset "Contraceptive Patch HCPCS Devices": 'urn:oid:2.16.840.1.113762.1.4.1166.149'
valueset "Contraceptive Patch ICD10CM Provision Encounters": 'urn:oid:2.16.840.1.113762.1.4.1166.146'
valueset "Contraceptive Patch ICD10CM Surveillance": 'urn:oid:2.16.840.1.113762.1.4.1166.147'
valueset "Contraceptive Patch LOINC": 'urn:oid:2.16.840.1.113762.1.4.1166.150'
valueset "Contraceptive Patch RXNORM Medications": 'urn:oid:2.16.840.1.113762.1.4.1166.76'
valueset "Contraceptive Patch SNOMED Devices": 'urn:oid:2.16.840.1.113762.1.4.1166.141'
valueset "Contraceptive Patch SNOMED Findings": 'urn:oid:2.16.840.1.113762.1.4.1166.145'
valueset "Contraceptive Patch SNOMED Provision Procedures": 'urn:oid:2.16.840.1.113762.1.4.1166.144'
valueset "Contraceptive Ring HCPCS Devices": 'urn:oid:2.16.840.1.113762.1.4.1166.159'
valueset "Contraceptive Ring ICD10CM Provision Encounters": 'urn:oid:2.16.840.1.113762.1.4.1166.156'
valueset "Contraceptive Ring ICD10CM Surveillance": 'urn:oid:2.16.840.1.113762.1.4.1166.157'
valueset "Contraceptive Ring LOINC": 'urn:oid:2.16.840.1.113762.1.4.1166.160'
valueset "Contraceptive Ring RXNORM Medications": 'urn:oid:2.16.840.1.113762.1.4.1166.129'
valueset "Contraceptive Ring SNOMED Findings": 'urn:oid:2.16.840.1.113762.1.4.1166.155'
valueset "Contraceptive Ring SNOMED Provision Procedures": 'urn:oid:2.16.840.1.113762.1.4.1166.154'
valueset "Contraceptive Ring SNOMED Surveillance Procedures": 'urn:oid:2.16.840.1.113762.1.4.1166.153'
valueset "Contraceptive Ring Surveillance": 'urn:oid:2.16.840.1.113762.1.4.1166.178'
valueset "Delivery Live Births": 'urn:oid:2.16.840.1.113883.3.464.1003.111.12.1015'
valueset "Estimated Delivery Date (EDD)": 'urn:oid:2.16.840.1.113762.1.4.1221.131'
valueset "Ethnicity": 'urn:oid:2.16.840.1.114222.4.11.837'
valueset "Female": 'urn:oid:2.16.840.1.113883.3.560.100.2'
valueset "Female Sterilization CPT Provision Procedures": 'urn:oid:2.16.840.1.113762.1.4.1166.93'
valueset "Female Sterilization HCPCS Devices": 'urn:oid:2.16.840.1.113762.1.4.1166.103'
valueset "Female Sterilization ICD10CM Provision Encounters": 'urn:oid:2.16.840.1.113762.1.4.1166.105'
valueset "Female Sterilization ICD10PCS Provision Procedures": 'urn:oid:2.16.840.1.113762.1.4.1166.99'
valueset "Female Sterilization LOINC": 'urn:oid:2.16.840.1.113762.1.4.1166.98'
valueset "Female Sterilization Provision Procedures": 'urn:oid:2.16.840.1.113762.1.4.1166.142'
valueset "Female Sterilization SNOMED Provision Procedures": 'urn:oid:2.16.840.1.113762.1.4.1166.134'
valueset "General Prenatal Care Visits": 'urn:oid:2.16.840.1.113762.1.4.1166.135'
valueset "Home Healthcare Services": 'urn:oid:2.16.840.1.113883.3.464.1003.101.12.1016'
valueset "Infecund Not for Contraceptive Reasons CPT Procedures": 'urn:oid:2.16.840.1.113762.1.4.1166.118'
valueset "Infecund Not for Contraceptive Reasons HCPCS Procedures": 'urn:oid:2.16.840.1.113762.1.4.1166.119'
valueset "Infecund Not for Contraceptive Reasons ICD10CM": 'urn:oid:2.16.840.1.113762.1.4.1166.97'
valueset "Infecund Not for Contraceptive Reasons Procedures": 'urn:oid:2.16.840.1.113762.1.4.1166.151'
valueset "Infecund Not for Contraceptive Reasons SNOMED Findings": 'urn:oid:2.16.840.1.113762.1.4.1166.96'
valueset "Infecund Not for Contraceptive Reasons SNOMED Procedures": 'urn:oid:2.16.840.1.113762.1.4.1166.165'
valueset "Injectable Contraceptive HCPCS Provision Procedures": 'urn:oid:2.16.840.1.113762.1.4.1166.187'
valueset "Injectable Contraceptive ICD10CM Provision Encounters": 'urn:oid:2.16.840.1.113762.1.4.1166.185'
valueset "Injectable Contraceptive ICD10CM Surveillance": 'urn:oid:2.16.840.1.113762.1.4.1166.186'
valueset "Injectable Contraceptive LOINC": 'urn:oid:2.16.840.1.113762.1.4.1166.188'
valueset "Injectable Contraceptive Provision Procedures": 'urn:oid:2.16.840.1.113762.1.4.1166.197'
valueset "Injectable Contraceptive RXNORM Medications": 'urn:oid:2.16.840.1.113762.1.4.1166.131'
valueset "Injectable Contraceptive SNOMED Findings": 'urn:oid:2.16.840.1.113762.1.4.1166.183'
valueset "Injectable Contraceptive SNOMED Provision Procedures": 'urn:oid:2.16.840.1.113762.1.4.1166.182'
valueset "Injectable Contraceptive SNOMED Surveillance Procedures": 'urn:oid:2.16.840.1.113762.1.4.1166.181'
valueset "Injectable Contraceptive Surveillance": 'urn:oid:2.16.840.1.113762.1.4.1166.198'
valueset "Intrauterine Device SNOMED Provision Procedures": 'urn:oid:2.16.840.1.113762.1.4.1166.88'
valueset "Intrauterine Devices HCPCS Devices": 'urn:oid:2.16.840.1.113762.1.4.1166.79'
valueset "Intrauterine Devices HCPCS Provision Procedures": 'urn:oid:2.16.840.1.113762.1.4.1166.81'
valueset "Intrauterine Devices ICD10CM Provision Encounters": 'urn:oid:2.16.840.1.113762.1.4.1166.83'
valueset "Intrauterine Devices ICD10CM Surveillance": 'urn:oid:2.16.840.1.113762.1.4.1166.84'
valueset "Intrauterine Devices ICD10PCS Provision Procedures": 'urn:oid:2.16.840.1.113762.1.4.1166.91'
valueset "Intrauterine Devices LOINC": 'urn:oid:2.16.840.1.113762.1.4.1166.80'
valueset "Intrauterine Devices RXNORM Medications": 'urn:oid:2.16.840.1.113762.1.4.1166.85'
valueset "Intrauterine Devices SNOMED Devices": 'urn:oid:2.16.840.1.113762.1.4.1166.86'
valueset "Intrauterine Devices SNOMED Findings": 'urn:oid:2.16.840.1.113762.1.4.1166.87'
valueset "Intrauterine Devices SNOMED Surveillance Procedures": 'urn:oid:2.16.840.1.113762.1.4.1166.89'
valueset "IUD Devices": 'urn:oid:2.16.840.1.113762.1.4.1166.140'
valueset "IUD Provision Procedures": 'urn:oid:2.16.840.1.113762.1.4.1166.139'
valueset "IUD Surveillance": 'urn:oid:2.16.840.1.113762.1.4.1166.138'
valueset "Non Live Birth CPT Procedures": 'urn:oid:2.16.840.1.113762.1.4.1166.127'
valueset "Non Live Birth Diagnoses": 'urn:oid:2.16.840.1.113762.1.4.1166.137'
valueset "Non Live Birth Diagnoses ICD10CM": 'urn:oid:2.16.840.1.113762.1.4.1166.125'
valueset "Non Live Birth Diagnoses SNOMED": 'urn:oid:2.16.840.1.113762.1.4.1166.126'
valueset "Non Live Birth ICD10PCS Procedures": 'urn:oid:2.16.840.1.113762.1.4.1166.128'
valueset "Non Live Birth Procedures": 'urn:oid:2.16.840.1.113762.1.4.1166.136'
valueset "Office Visit": 'urn:oid:2.16.840.1.113883.3.464.1003.101.12.1001'
valueset "ONC Administrative Sex": 'urn:oid:2.16.840.1.113762.1.4.1'
valueset "Oral Contraceptive Pill HCPCS Provision Procedures": 'urn:oid:2.16.840.1.113762.1.4.1166.195'
valueset "Oral Contraceptive Pill ICD10CM Provision Encounters": 'urn:oid:2.16.840.1.113762.1.4.1166.193'
valueset "Oral Contraceptive Pill ICD10CM Surveillance": 'urn:oid:2.16.840.1.113762.1.4.1166.194'
valueset "Oral Contraceptive Pill LOINC": 'urn:oid:2.16.840.1.113762.1.4.1166.196'
valueset "Oral Contraceptive Pill Provision Procedures": 'urn:oid:2.16.840.1.113762.1.4.1166.199'
valueset "Oral Contraceptive Pill SNOMED Findings": 'urn:oid:2.16.840.1.113762.1.4.1166.191'
valueset "Oral Contraceptive Pill SNOMED Provision Procedures": 'urn:oid:2.16.840.1.113762.1.4.1166.190'
valueset "Oral Contraceptive Pill SNOMED Surveillance Procedures": 'urn:oid:2.16.840.1.113762.1.4.1166.189'
valueset "Oral Contraceptive Pill Surveillance": 'urn:oid:2.16.840.1.113762.1.4.1166.200'
valueset "Oral Contraceptive Pills RXNORM Medications": 'urn:oid:2.16.840.1.113762.1.4.1166.132'
valueset "Payer": 'urn:oid:2.16.840.1.114222.4.11.3591'
valueset "Pregnancy Bundle CPT": 'urn:oid:2.16.840.1.113762.1.4.1166.168'
valueset "Pregnancy Bundle HCPCS": 'urn:oid:2.16.840.1.113762.1.4.1166.169'
valueset "Pregnancy Bundle Visits": 'urn:oid:2.16.840.1.113762.1.4.1166.110'
valueset "Pregnancy Related Diagnoses": 'urn:oid:2.16.840.1.113762.1.4.1166.133'
valueset "Pregnancy Related Diagnoses ICD10CM": 'urn:oid:2.16.840.1.113762.1.4.1166.123'
valueset "Pregnancy Related Diagnoses SNOMED": 'urn:oid:2.16.840.1.113762.1.4.1166.124'
valueset "Prenatal Care Specific Visits": 'urn:oid:2.16.840.1.113762.1.4.1166.114'
valueset "Prenatal Care Specific Visits CPT": 'urn:oid:2.16.840.1.113762.1.4.1166.111'
valueset "Prenatal Care Specific Visits HCPCS": 'urn:oid:2.16.840.1.113762.1.4.1166.112'
valueset "Prenatal Care Specific Visits SNOMED": 'urn:oid:2.16.840.1.113762.1.4.1166.113'
valueset "Prenatal Care Visits CPT": 'urn:oid:2.16.840.1.113762.1.4.1166.120'
valueset "Prenatal Care Visits HCPCS": 'urn:oid:2.16.840.1.113762.1.4.1166.121'
valueset "Prenatal Care Visits SNOMED": 'urn:oid:2.16.840.1.113762.1.4.1166.122'
valueset "Preventive Care Services Established Office Visit, 18 and Up": 'urn:oid:2.16.840.1.113883.3.464.1003.101.12.1025'
valueset "Preventive Care Services Initial Office Visit, 18 and Up": 'urn:oid:2.16.840.1.113883.3.464.1003.101.12.1023'
valueset "Preventive Care Services, Initial Office Visit, 0 to 17": 'urn:oid:2.16.840.1.113883.3.464.1003.101.12.1022'
valueset "Preventive Care, Established Office Visit, 0 to 17": 'urn:oid:2.16.840.1.113883.3.464.1003.101.12.1024'
valueset "Race": 'urn:oid:2.16.840.1.114222.4.11.836'
valueset "Self Identified Need for Contraception (SINC)": 'urn:oid:2.16.840.1.113762.1.4.1166.115'
valueset "Sterilization SNOMED Findings": 'urn:oid:2.16.840.1.113762.1.4.1166.109'

code "Do you want to talk about contraception or pregnancy prevention during your visit today": '98076-3' from "LOINC" display 'Do you want to talk about contraception or pregnancy prevention during your visit today'
code "No - I am already using contraception": 'LA32393-3' from "LOINC" display 'No - I am already using contraception'
code "No - I am hoping to become pregnant in the near future": 'LA32392-5' from "LOINC" display 'No - I am hoping to become pregnant in the near future'
code "No - I am unsure or dont want to use contraception": 'LA32391-7' from "LOINC" display 'No - I am unsure or dont want to use contraception'
code "No - I do not want to talk about contraception today because I am here for something else": 'LA32389-1' from "LOINC" display 'No - I do not want to talk about contraception today because I am here for something else'
code "No - This question does not apply to me/I prefer not to answer": 'LA32390-9' from "LOINC" display 'No - This question does not apply to me/I prefer not to answer'
code "Yes": 'LA33-6' from "LOINC" display 'Yes'

parameter "Measurement Period" Interval<DateTime>

context Patient

define "Contraceptive Patch":
 ( ["Medication, Order": "Contraceptive Patch Devices"] )
   union ( ["Medication, Order": "Contraceptive Patch HCPCS Devices"] )
   union ( ["Encounter, Performed": "Contraceptive Patch ICD10CM Provision Encounters"] )
   union ( ["Assessment, Performed": "Contraceptive Patch ICD10CM Surveillance"] )
   union ( ["Assessment, Performed": "Contraceptive Patch LOINC"] )
   union ( ["Medication, Order": "Contraceptive Patch RXNORM Medications"] )
   union ( ["Medication, Order": "Contraceptive Patch SNOMED Devices"] )
   union ( ["Assessment, Performed": "Contraceptive Patch SNOMED Findings"] )

define "Contraceptive Ring":
 ( ["Medication, Order": "Contraceptive Ring HCPCS Devices"] )
   union ( ["Encounter, Performed": "Contraceptive Ring ICD10CM Provision Encounters"] )
   union ( ["Assessment, Performed": "Contraceptive Ring ICD10CM Surveillance"] )
   union ( ["Medication, Order": "Contraceptive Ring LOINC"] )
   union ( ["Assessment, Performed": "Contraceptive Ring SNOMED Findings"] )
   union ( ["Procedure, Performed": "Contraceptive Ring SNOMED Provision Procedures"] )
   union ( ["Intervention, Order": "Contraceptive Ring SNOMED Surveillance Procedures"] )
   union ( ["Assessment, Performed": "Contraceptive Ring Surveillance"] )

define "Denominator Exclusion":
 (
   exists ( "Live Birth Time Period" )
    or (
      exists ("Estimated Delivery Date")
        //and exists ( "AW PNC Visits" ) // Expression not defined?
        and ( "Non Live Births" ) is null
    )
    or ( exists ( "Infecund" ) )
    or ( exists ( "SINC No" )  and ("MostMod Contraception") is null )
  )

define "Injectables":
 ( ["Procedure, Performed": "Injectable Contraceptive HCPCS Provision Procedures"] )
   union ( ["Encounter, Performed": "Injectable Contraceptive ICD10CM Provision Encounters"] )
   union ( ["Assessment, Performed": "Injectable Contraceptive ICD10CM Surveillance"] )
   union ( ["Medication, Order": "Injectable Contraceptive LOINC"] )
   union ( ["Procedure, Performed": "Injectable Contraceptive Provision Procedures"] )
   union ( ["Medication, Order": "Injectable Contraceptive RXNORM Medications"] )
   union ( ["Assessment, Performed": "Injectable Contraceptive SNOMED Findings"] )
   union ( ["Procedure, Performed": "Injectable Contraceptive SNOMED Provision Procedures"] )
   union ( ["Procedure, Performed": "Injectable Contraceptive SNOMED Surveillance Procedures"] )

define "Is Female":
 exists ["Patient Characteristic Sex": "Female"]

define "LARC Numerator":
 ( exists ( "LARC Provisions" ) )
   and ( "Initial Population" )

define "LARC Provisions":
 ( ( ["Encounter, Performed": "Contraceptive Implant ICD10CM Provision Encounters"] )
   union ( ["Procedure, Performed": "Contraceptive Implant Provision Procedures"] )
   union ( ["Medication, Order": "Contraceptive Implants RXNORM Medications"] )
   union ( ["Medication, Order": "Contraceptive Implant LOINC"] )
   union ( ["Device, Order": "Contraceptive Implant Devices"] )
   union ( ["Encounter, Performed": "Intrauterine Devices ICD10CM Provision Encounters"] )
   union ( ["Procedure, Performed": "IUD Provision Procedures"] )
   union ( ["Medication, Order": "Intrauterine Devices RXNORM Medications"] )
   union ( ["Medication, Order": "Intrauterine Devices LOINC"] )
   union ( ["Device, Order": "IUD Devices"] ) ) LARCProv
   where LARCProv.relevantPeriod during "Measurement Period"

define "LARC Surveillance":
 ( ( ["Encounter, Performed": "Intrauterine Devices ICD10CM Surveillance"] )
   union ( ["Assessment, Performed": "Intrauterine Devices SNOMED Findings"] )
   union ( ["Procedure, Performed": "Intrauterine Devices SNOMED Surveillance Procedures"] )
   union ( ["Encounter, Performed": "Contraceptive Implant ICD10CM Surveillance"] )
   union ( ["Assessment, Performed": "Contraceptive Implant SNOMED Findings"] )
   union ( ["Procedure, Performed": "Contraceptive Implant SNOMED Surveillance Procedures"] ) ) LARCSurv
   where LARCSurv.relevantPeriod during "Measurement Period"

define "Live Birth Time Period":
 ["Encounter, Performed": "Delivery Live Births"] LiveBirths
   where LiveBirths.relevantPeriod overlaps Interval ( start of "Measurement Period" - 3 months,
   end of "Measurement Period" )
     //and exists ( "Prenatal Care Visits" )  // Expression not defined?
     and ( "Initial Population" )

define "Live Births":
 ["Encounter, Performed": "Delivery Live Births"]

define "MostMod Contraception":
 ( "Contraceptive Patch"
     union "Contraceptive Ring"
     union "Female Sterilization"
     union "Injectables"
     union "Oral Contraceptives"
     union "LARC Provisions"
     union "LARC Surveillance"
 )

define "MostMod Exclusion":
 ( "MostMod Contraception" ) is null

define "MostMod Numerator":
 ( exists ( "MostMod Contraception" )
    and ( "Initial Population" )
 )

define "Non Live Births":
 ( ["Procedure, Performed": "Non Live Birth CPT Procedures"] )
   union ( ["Diagnosis": "Non Live Birth Diagnoses"] )

define "Oral Contraceptives":
 ( ["Medication, Order": "Oral Contraceptive Pill HCPCS Provision Procedures"] )
   union ( ["Encounter, Performed": "Oral Contraceptive Pill ICD10CM Provision Encounters"] )
   union ( ["Assessment, Performed": "Oral Contraceptive Pill ICD10CM Surveillance"] )
   union ( ["Medication, Order": "Oral Contraceptive Pill LOINC"] )
   union ( ["Procedure, Performed": "Oral Contraceptive Pill Provision Procedures"] )
   union ( ["Assessment, Performed": "Oral Contraceptive Pill SNOMED Findings"] )
   union ( ["Procedure, Performed": "Oral Contraceptive Pill SNOMED Provision Procedures"] )
   union ( ["Procedure, Performed": "Oral Contraceptive Pill SNOMED Surveillance Procedures"] )
   union ( ["Assessment, Performed": "Oral Contraceptive Pill Surveillance"] )
   union ( ["Medication, Order": "Oral Contraceptive Pills RXNORM Medications"] )

define "SDE Ethnicity":
 ["Patient Characteristic Ethnicity": "Ethnicity"]

define "SDE Payer":
 ["Patient Characteristic Payer": "Payer"]

define "SDE Race":
 ["Patient Characteristic Race": "Race"]

define "SDE Sex":
 ["Patient Characteristic Sex": "ONC Administrative Sex"]

define "SINC Missing":
 ["Assessment, Order": "Self Identified Need for Contraception (SINC)"] is null

define "SINC No":
 ["Assessment, Performed": "No - I am hoping to become pregnant in the near future"]
   union ( ["Assessment, Performed": "No - I do not want to talk about contraception today because I am here for something else"] )
   union ( ["Assessment, Performed": "No - This question does not apply to me/I prefer not to answer"] )
   union ( ["Assessment, Performed": "No - I am unsure or dont want to use contraception"] )
   union ( ["Assessment, Performed": "No - I am already using contraception"] )

define "SINC Yes":
 ["Assessment, Performed": "Yes"]

define "Estimated Delivery Date":
 ["Assessment, Performed": "Estimated Delivery Date (EDD)"] EDD
   where EDD.relevantPeriod overlaps Interval ( start of "Measurement Period" - 3 months, start of "Measurement Period" + 9 months )

define "Female Sterilization":
 ( ( ["Device, Order": "Female Sterilization HCPCS Devices"] )
   union ( ["Procedure, Performed": "Female Sterilization Provision Procedures"] )
   union ( ["Encounter, Performed": "Female Sterilization ICD10CM Provision Encounters"] )
   union ( ["Medication, Order": "Female Sterilization LOINC"] )
   union ( ["Assessment, Performed": "Sterilization SNOMED Findings"] ) ) Steril
   where Steril.relevantPeriod during "Measurement Period"

define "Infecund":
 ( ( ["Procedure, Performed": "Infecund Not for Contraceptive Reasons CPT Procedures"] )
 union ( ["Procedure, Performed": "Infecund Not for Contraceptive Reasons HCPCS Procedures"] )
 union ( ["Encounter, Performed": "Infecund Not for Contraceptive Reasons ICD10CM"] )
 union ( ["Procedure, Performed": "Infecund Not for Contraceptive Reasons Procedures"] )
 union ( ["Assessment, Performed": "Infecund Not for Contraceptive Reasons SNOMED Findings"] )
 union ( ["Procedure, Performed": "Infecund Not for Contraceptive Reasons SNOMED Procedures"] ) )

define "EncounterInMeasurementPeriod":
 ( ["Encounter, Performed": "Office Visit"] )
   union ( ["Encounter, Performed": "Preventive Care Services Established Office Visit, 18 and Up"] )
   union ( ["Encounter, Performed": "Preventive Care Services Initial Office Visit, 18 and Up"] )
   union ( ["Encounter, Performed": "Preventive Care Services, Initial Office Visit, 0 to 17"] )
   union ( ["Encounter, Performed": "Preventive Care, Established Office Visit, 0 to 17"] )
   union ( ["Encounter, Performed": "Home Healthcare Services"] ) ValidEncounter
     where ValidEncounter.relevantPeriod during "Measurement Period"

define "All Women Denominator":
 "Initial Population"

define "Initial Population":
 AgeInYearsAt(start of "Measurement Period") >= 15
     and AgeInYearsAt(start of "Measurement Period") <= 44
     and ("Is Female") and exists ( "EncounterInMeasurementPeriod" )

/*******************************************************************************************************************
ERRORS:
********************************************************************************************************************
Line 161: Syntax error at define

Line 177: Could not validate reference to expression Initial Population because its definition contains errors.

Line 205: Could not resolve identifier Prenatal Care Visits in the current library.

Line 228: Syntax error at define

Line 289: Syntax error at define

Line 299: Could not validate reference to expression Initial Population because its definition contains errors.

Line 302: Could not resolve identifier MeasurementPeriod in the current library.
*******************************************************************************************************************/
